feat: added additional headers to clickhouse requests
ClickHouse/clickhouse-js pull request #224
Opened 2024-01-17 16:47 UTC by teawithfruit

## Summary
This PR enables clickhouse-js to use additional headers in http(s) requests. On my side it was necessary to be able to use a reverse proxy with basic auth in front. For example, something like this is possible from now on.

```ts
createClient({
  host: 'https://log.example.com',
  username: 'basic_auth_user',
  password: 'basic_auth_password',
  additionalHeaders: {
    'X-ClickHouse-User': 'clickhouse_user',
    'X-ClickHouse-Key': 'clickhouse_password',
  },
});
```

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

2024-01-17 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-js?pullRequest=224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-js?pullRequest=224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-js?pullRequest=224) it.</sub>

2024-01-17 17:07 UTC, slvrtrn requested changes
Can you please 
- add these options to the web version as well
- add tests - for the web version, the suitable place likely will be in `packages/client-web/__tests__/integration/web_connection.test.ts` (fetch stubs are already there, should be easy to assert on headers); for Node.js, a similar one can be created as `packages/client-node/__tests__/integration/node_connection.test.ts` as we want to test the entire interaction (client options -> connection -> request). There are also examples of [http.request stubs here](https://github.com/ClickHouse/clickhouse-js/blob/20bd2868a2b5caf372fc501431c1bafb7d9a9758/packages/client-node/__tests__/unit/node_http_adapter.test.ts#L23-L24).

2024-01-17 17:07 UTC, slvrtrn commented on packages/client-common/src/client.ts
> +  additionalHeaders?: object
Let's keep it in snake_case as the rest, and change the type to `Record<string, number | string | string[]>` to be more in line with the OutgoingHttpHeaders type.

2024-01-17 17:07 UTC, slvrtrn commented on packages/client-common/src/client.ts
> +    additionalHeaders: config.additionalHeaders ?? {},
It can be just `additional_headers?` without `??` as it is in `connection.ts`, i.e. we are ok with an undefined.

2024-01-19 16:47 UTC, merged

2024-01-19 17:46 UTC, slvrtrn commented
@teawithfruit, thanks for the contribution. I took the liberty to do some fixups in the tests, plus I noticed that `Record<string, number | string | string[]>` was a bit too permissive (`fetch` API is a bit more strict on that), so I reduced it to `Record<string, string>` as it matches both APIs.

Released as [0.2.9](https://github.com/ClickHouse/clickhouse-js/releases/tag/0.2.9).

2024-01-19 18:15 UTC, teawithfruit commented
Thanks for reacting such fast. 🙂